---
sidebar: sidebar 
permalink: reference_default_configs.html 
keywords: svm, LIF, LIFs, configuration backups, attributes, autosize, security style, space guarantee, unix permissions, NTFS, UNIX, boot, root, disks, aggr0, aggr1, svm, svms, storage virtual machine, LIF failover, failover, attributes, volume attributes, boot disk, root disk, licenses, feature licenses, default licenses, ontap licenses, ontap features 
summary: Comprender cómo se configura Cloud Volumes ONTAP de forma predeterminada puede ayudarle a configurar y administrar los sistemas, especialmente si está familiarizado con ONTAP porque la configuración predeterminada para Cloud Volumes ONTAP es diferente de ONTAP. 
---
= Configuración predeterminada de Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Comprender cómo se configura Cloud Volumes ONTAP de forma predeterminada puede ayudarle a configurar y administrar los sistemas, especialmente si está familiarizado con ONTAP porque la configuración predeterminada para Cloud Volumes ONTAP es diferente de ONTAP.



== Valores predeterminados

* Cloud Volumes ONTAP está disponible como un sistema de un solo nodo en AWS, Azure y GCP, así como como una pareja de alta disponibilidad en AWS y Azure.
* Cloud Manager crea una máquina virtual de almacenamiento que sirve datos cuando pone en marcha Cloud Volumes ONTAP. Algunas configuraciones admiten máquinas virtuales de almacenamiento adicionales. link:task_managing_svms.html["Obtenga más información sobre la gestión de máquinas virtuales de almacenamiento"].
* Cloud Manager instala automáticamente las siguientes licencias de funciones de ONTAP en Cloud Volumes ONTAP:
+
** CIFS
** FlexCache
** FlexClone
** ISCSI
** Cifrado de volúmenes de NetApp (solo para sistemas BYOL o registrados de PAYGO)
** NFS
** SnapMirror
** SnapRestore
** SnapVault


* De forma predeterminada, se crean varias interfaces de red:
+
** Una LIF de gestión de clústeres
** Una LIF de interconexión de clústeres
** Una LIF de gestión SVM en sistemas de alta disponibilidad en Azure, sistemas de un solo nodo en AWS y, opcionalmente, en sistemas de alta disponibilidad en varias zonas de disponibilidad de AWS
** Una LIF de gestión de nodos
** Una LIF de datos iSCSI
** Un LIF de datos CIFS y NFS
+

NOTE: La conmutación por error de LIF está deshabilitada de forma predeterminada para Cloud Volumes ONTAP debido a los requisitos de EC2. Al migrar una LIF a otro puerto, se interrumpe la asignación externa entre direcciones IP e interfaces de red en la instancia, lo que hace que la LIF no sea accesible.



* Cloud Volumes ONTAP envía backups de configuración al conector mediante HTTPS.
+
Se puede acceder a los backups desde https://ipaddress/occm/offboxconfig/[] Donde _ipaddress_ es la dirección IP del host del conector.

* Cloud Manager establece algunos atributos de volumen de manera diferente a los de otras herramientas de gestión (por ejemplo, System Manager o la CLI).
+
En la siguiente tabla, se enumeran los atributos de volúmenes que Cloud Manager establece de manera diferente a los valores predeterminados:

+
[cols="15,85"]
|===
| Atributo | Valor definido por Cloud Manager 


| Modo de ajuste automático de tamaño | crezca 


| tamaño automático máximo  a| 
1,000 por ciento


NOTE: El administrador de cuentas puede modificar este valor en la página Configuración.



| Estilo de seguridad | NTFS para volúmenes CIFS UNIX para volúmenes NFS 


| Estilo de garantía de espacio | ninguno 


| Permisos de UNIX (solo NFS) | 777 
|===
+
Consulte la página del comando man _volume create_ para obtener información sobre estos atributos.





== Datos raíz y de arranque para Cloud Volumes ONTAP

Además del almacenamiento de los datos de usuario, Cloud Manager también adquiere almacenamiento en cloud para el arranque y los datos raíz en cada sistema Cloud Volumes ONTAP.



=== AWS

* Dos discos por nodo para arranque y datos raíz:
+
** 9.7: Disco io1 de 160 GB para datos de arranque y un disco gp2 de 220 GB para datos raíz
** 9.6: Disco io1 de 93 GB para datos de arranque y un disco gp2 de 140 GB para datos raíz
** 9.5: Disco io1 de 45 GB para datos de arranque y un disco gp2 de 140 GB para datos raíz


* Una instantánea de EBS para cada disco de arranque y disco raíz
* Para los pares de alta disponibilidad, un volumen de EBS para la instancia de Mediator, que es aproximadamente 8 GB




=== Azure (nodo único)

* Tres discos SSD premium:
+
** Un disco de 10 GB para los datos de arranque
** Un disco de 140 GB para datos raíz
** Un disco de 128 GB para NVRAM
+
Si la máquina virtual elegida para Cloud Volumes ONTAP admite Ultra SSD, el sistema utiliza un Ultra SSD para NVRAM, en lugar de un SSD Premium.



* Un disco duro estándar de 1024 GB para ahorrar núcleos
* Una instantánea de Azure para cada disco de arranque y disco raíz




=== Azure (parejas de alta disponibilidad)

* Dos discos SSD Premium de 10 GB para el volumen de arranque (uno por nodo)
* Dos Blobs de página de almacenamiento Premium de 140 GB para la raíz volumen (uno por nodo)
* Dos discos HDD estándar de 1024 GB para ahorrar núcleos (uno por nodo)
* Dos discos SSD Premium de 128 GB para NVRAM (uno por nodo)
* Una instantánea de Azure para cada disco de arranque y disco raíz




=== GCP

* Un disco persistente estándar de 10 GB para datos de arranque
* Un disco persistente estándar de 64 GB para datos raíz
* Un disco persistente estándar de 500 GB para NVRAM
* Un disco persistente estándar de 216 GB para ahorrar núcleos
* Una instantánea de GCP para el disco de arranque y la raíz disco




=== La ubicación de los discos

Cloud Manager establece el almacenamiento de la siguiente manera:

* Los datos de arranque residen en un disco asociado a la instancia o a la máquina virtual.
+
Este disco, que contiene la imagen de arranque, no está disponible para Cloud Volumes ONTAP.

* Los datos raíz, que contienen la configuración y los registros del sistema, residen en aggr0.
* El volumen raíz de la máquina virtual de almacenamiento (SVM) reside en aggr1.
* Los volúmenes de datos también residen en aggr1.




=== Cifrado

Los discos de arranque y raíz siempre se cifran en Azure y Google Cloud Platform, ya que el cifrado está habilitado de forma predeterminada en esos proveedores de cloud.

Cuando habilita el cifrado de datos en AWS mediante el Servicio de gestión de claves (KMS), los discos de arranque y raíz para Cloud Volumes ONTAP también se cifran. Esto incluye el disco de arranque para la instancia del mediador en una pareja de alta disponibilidad. Los discos se cifran utilizando el CMK que seleccione al crear el entorno de trabajo.
