---
sidebar: sidebar 
permalink: task_sync_licensing.html 
keywords: license, subscription, registering, subscribing, subscribing in aws, subscribing in azure, subscribing to aws, subscribing to azure, aws marketplace, azure marketplace, netapp license, byol license, purchase a license, license settings, pay for relationships, paygo, annual, pay-as-you-go 
summary: Hay dos formas de pagar las relaciones de sincronización después de que termine su prueba gratuita de 14 días. La primera opción es el pago por uso. La segunda opción consiste en comprar licencias directamente a NetApp. 
---
= Pago de las relaciones de sincronización después de que finalice su prueba gratuita
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


Hay dos formas de pagar las relaciones de sincronización después de que termine su prueba gratuita de 14 días. La primera opción es suscribirse a AWS o Azure para pagar por uso o anualmente. La segunda opción consiste en comprar licencias directamente a NetApp.

Puede usar licencias de NetApp con una suscripción a AWS o Azure. Por ejemplo, si tiene 25 relaciones de sincronización, puede pagar las primeras 20 relaciones de sincronización con una licencia y, a continuación, pagar por el uso desde AWS o Azure con las 5 relaciones de sincronización restantes.

link:concept_cloud_sync.html["Obtenga más información sobre cómo funcionan las licencias"].

.¿Qué pasa si no 8217 pago inmediatamente después de que finalice mi prueba gratuita?
****
No podrá crear relaciones adicionales. Las relaciones existentes no se eliminan, pero no puede realizar ningún cambio hasta que se suscriba o introduzca una licencia.

****


== [[aws]]Suscribirse a AWS

AWS le permite pagar anualmente.

.De pago por uso
. Haga clic en *Sincronizar > licencias*.
. Seleccione *AWS*
. Haga clic en *Suscribirse* y, a continuación, en *continuar*.
. Suscríbase desde el mercado de AWS y, a continuación, vuelva a iniciar sesión en el servicio Cloud Sync para completar el registro.
+
El siguiente vídeo muestra el proceso:

+
video::video_cloud_sync_registering.mp4[width=848,height=480]


.Pasos a pagar anualmente
. https://aws.amazon.com/marketplace/pp/B06XX5V3M2["Vaya a la página AWS Marketplace"^].
. Haga clic en *continuar para suscribirse*.
. Seleccione sus opciones de contrato y haga clic en *Crear contrato*.




== [[Azure]]suscribirse de Azure

Azure le permite pagar por uso o anualmente.

.Lo que necesitará
Cuenta de usuario de Azure con permisos de colaborador o propietario en la suscripción correspondiente.

.Pasos
. Haga clic en *Sincronizar > licencias*.
. Seleccione *Azure*.
. Haga clic en *Suscribirse* y, a continuación, en *continuar*.
. En el portal de Azure, haga clic en *Crear*, seleccione sus opciones y haga clic en *Suscribirse*.
+
Seleccione *Mensual* para pagar por hora, o *Anual* para pagar por un año antes de la fecha.

. Una vez completada la implementación, haga clic en el nombre del recurso SaaS en la ventana emergente de notificaciones.
. Haga clic en *Configurar cuenta* para volver a Cloud Sync.
+
El siguiente vídeo muestra el proceso:

+
video::video_cloud_sync_registering_azure.mp4[width=848,height=480]




== [[licencias]]Compra de licencias de NetApp y añadirlas a Cloud Sync

Para pagar por adelantado sus relaciones de sincronización, debe adquirir una o más licencias y añadirlas al servicio de Cloud Sync.

.Pasos
. Adquiera una licencia por correo electrónico:ng-cloudsync-contact@netapp.com?Subject=Cloud%20Sync%20Service%20-%20BYOL%20Licencia%20Compra%20Solicite[Contacto con NetApp].
. En Cloud Manager, haga clic en *sincronización > licencias*.
. Haga clic en *Agregar licencia* y agregue la licencia.

