---
sidebar: sidebar 
permalink: task_provisioning_storage.html 
keywords: storage, provisioning, iscsi, nfs, cifs, volumes, aggregates, provision, create, quotas, nas, san, LUNs, quotas, qtree, add, advanced allocation, create a volume, add a volume, create volumes, add volumes, creating a volume, adding a volume, creating aggregates, adding an aggregate, add an aggregate, create an aggregate, provision volume, provision a volume, provisioning volumes, create a LUN, create LUNs, create LUN, provision LUNs, add volume to second node, add volume to node 2, flexcache, flexcache volumes, create a flexcache volume, provision flexcache, create flexcache volume 
summary: Puede aprovisionar almacenamiento adicional de NFS, CIFS e iSCSI para sus sistemas Cloud Volumes ONTAP desde Cloud Manager gestionando volúmenes y agregados. 
---
= Aprovisionar almacenamiento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede aprovisionar almacenamiento adicional para los sistemas Cloud Volumes ONTAP desde Cloud Manager mediante la gestión de volúmenes y agregados.


IMPORTANT: Todos los discos y agregados deben crearse y eliminarse directamente desde Cloud Manager. No debe realizar estas acciones desde otra herramienta de gestión. De esta manera, se puede afectar a la estabilidad del sistema, se puede obstaculizar la capacidad de añadir discos en el futuro y generar potencialmente cuotas redundantes para proveedores de cloud.



== Creación de volúmenes de FlexVol

Si necesita más almacenamiento después de iniciar un sistema Cloud Volumes ONTAP, puede crear nuevos volúmenes FlexVol para NFS, CIFS o iSCSI desde Cloud Manager.

.Acerca de esta tarea
Cuando se crea un volumen iSCSI, Cloud Manager crea automáticamente un LUN. Lo hemos hecho sencillo creando sólo una LUN por volumen, por lo que no hay que realizar ninguna gestión. Después de crear el volumen, <<Conectar una LUN a un host,Utilice el IQN para conectarse con la LUN del hosts>>.


NOTE: Puede crear LUN adicionales desde System Manager o desde la CLI.

.Antes de empezar
Si desea usar CIFS en AWS, debe haber configurado DNS y Active Directory. Para obtener más información, consulte link:reference_networking_aws.html["Requisitos de red para Cloud Volumes ONTAP para AWS"].

.Pasos
. En la página Working Environments, haga doble clic en el nombre del sistema Cloud Volumes ONTAP donde desea aprovisionar los volúmenes de FlexVol.
. Cree un nuevo volumen en cualquier agregado o en un agregado específico:
+
[cols="30,70"]
|===
| Acción | Pasos 


| Cree un nuevo volumen y deje que Cloud Manager elija el con el agregado | Haga clic en *Añadir nuevo volumen*. 


| Cree un nuevo volumen en un agregado específico  a| 
.. Haga clic en el icono de menú y, a continuación, haga clic en *Avanzado > asignación avanzada*.
.. Haga clic en el menú de un agregado.
.. Haga clic en *Crear volumen*.


|===
. Introduzca los detalles del nuevo volumen y, a continuación, haga clic en *continuar*.
+
Algunos de los campos en esta página son claros y explicativos. En la siguiente tabla se describen los campos que podrían presentar dificultades:

+
[cols="25,75"]
|===
| Campo | Descripción 


| Tamaño | El tamaño máximo que puede introducir depende en gran medida de si habilita thin provisioning, lo que le permite crear un volumen que sea mayor que el almacenamiento físico que hay disponible actualmente. 


| Control de acceso (solo para NFS) | Una política de exportación define los clientes de la subred que pueden acceder al volumen. De forma predeterminada, Cloud Manager introduce un valor que proporciona acceso a todas las instancias de la subred. 


| Permisos y usuarios/grupos (solo para CIFS) | Estos campos permiten controlar el nivel de acceso a un recurso compartido para usuarios y grupos (también denominados listas de control de acceso o ACL). Es posible especificar usuarios o grupos de Windows locales o de dominio, o usuarios o grupos de UNIX. Si especifica un nombre de usuario de Windows de dominio, debe incluir el dominio del usuario con el formato domain\username. 


| Política de Snapshot | Una política de copia de Snapshot especifica la frecuencia y el número de copias de Snapshot de NetApp creadas automáticamente. Una copia snapshot de NetApp es una imagen del sistema de archivos puntual que no afecta al rendimiento y requiere un almacenamiento mínimo. Puede elegir la directiva predeterminada o ninguna. Es posible que no elija ninguno para los datos transitorios: Por ejemplo, tempdb para Microsoft SQL Server. 


| Opciones avanzadas (solo para NFS) | Seleccione una versión de NFS para el volumen: NFSv3 o NFSv4. 


| Grupo del iniciador y IQN (solo para iSCSI) | Los destinos de almacenamiento iSCSI se denominan LUN (unidades lógicas) y se presentan a los hosts como dispositivos de bloque estándar. Los iGroups son tablas de los nombres de los nodos de host iSCSI y controlan qué iniciadores tienen acceso a qué LUN. Los destinos iSCSI se conectan a la red a través de adaptadores de red Ethernet (NIC) estándar, tarjetas DEL motor de descarga TCP (TOE) con iniciadores de software, adaptadores de red convergente (CNA) o adaptadores de host de salida dedicados (HBA) y se identifican mediante nombres cualificados de iSCSI (IQN). Cuando se crea un volumen iSCSI, Cloud Manager crea automáticamente un LUN. Lo hemos hecho sencillo creando sólo una LUN por volumen, por lo que no hay que realizar ninguna gestión. Después de crear el volumen, link:task_provisioning_storage.html#connecting-a-lun-to-a-host["Utilice el IQN para conectarse con la LUN del hosts"]. 
|===
. Si ha elegido el protocolo CIFS y no se ha configurado el servidor CIFS, especifique los detalles del servidor en el cuadro de diálogo Crear un servidor CIFS y, a continuación, haga clic en *Guardar y continuar*:
+
[cols="30,70"]
|===
| Campo | Descripción 


| DNS Dirección IP principal y secundaria | Las direcciones IP de los servidores DNS que proporcionan resolución de nombres para el servidor CIFS. Los servidores DNS enumerados deben contener los registros de ubicación de servicio (SRV) necesarios para localizar los servidores LDAP de Active Directory y los controladores de dominio del dominio al que se unirá el servidor CIFS. 


| Dominio de Active Directory al que unirse | El FQDN del dominio de Active Directory (AD) al que desea que se una el servidor CIFS. 


| Credenciales autorizadas para unirse al dominio | Nombre y contraseña de una cuenta de Windows con privilegios suficientes para agregar equipos a la unidad organizativa (OU) especificada dentro del dominio AD. 


| Nombre NetBIOS del servidor CIFS | Nombre de servidor CIFS que es único en el dominio de AD. 


| Unidad organizacional  a| 
La unidad organizativa del dominio AD para asociarla con el servidor CIFS. El valor predeterminado es CN=Computers.

** Para configurar Microsoft AD administrado de AWS como el servidor AD para Cloud Volumes ONTAP, debe introducir *OU=equipos,OU=corp* en este campo.
** Para configurar los Servicios de dominio de Azure AD como servidor AD para Cloud Volumes ONTAP, debe introducir *OU=equipos ADDC* o *OU=usuarios ADDC* en este campo.https://docs.microsoft.com/en-us/azure/active-directory-domain-services/create-ou["Documentación de Azure: Cree una unidad organizativa (OU) en un dominio gestionado de Azure AD Domain Services"^]




| Dominio DNS | El dominio DNS para la máquina virtual de almacenamiento (SVM) de Cloud Volumes ONTAP. En la mayoría de los casos, el dominio es el mismo que el dominio de AD. 


| Servidor NTP | Seleccione *usar dominio de Active Directory* para configurar un servidor NTP mediante el DNS de Active Directory. Si necesita configurar un servidor NTP con una dirección diferente, debe usar la API. Consulte link:api.html["Guía para desarrolladores de API de Cloud Manager"^] para obtener más detalles. 
|===
. En la página Usage Profile, Disk Type y Tiering Policy, elija si desea habilitar las funciones de eficiencia del almacenamiento, elija un tipo de disco y edite la política de organización en niveles, si es necesario.
+
Si necesita ayuda, consulte lo siguiente:

+
** link:task_planning_your_config.html#choosing-a-volume-usage-profile["Descripción de los perfiles de uso de volumen"]
** link:task_planning_your_config.html#sizing-your-system-in-aws["Ajuste de tamaño de su sistema en AWS"]
** link:task_planning_your_config.html#sizing-your-system-in-azure["Ajuste de tamaño de su sistema en Azure"]
** link:concept_data_tiering.html["Información general sobre organización en niveles de datos"]


. Haga clic en *Ir*.


.Resultado
Cloud Volumes ONTAP aprovisiona el volumen.

.Después de terminar
Si ha aprovisionado un recurso compartido CIFS, proporcione permisos a usuarios o grupos a los archivos y carpetas y compruebe que esos usuarios pueden acceder al recurso compartido y crear un archivo.

Si desea aplicar cuotas a volúmenes, debe usar System Manager o la interfaz de línea de comandos. Las cuotas le permiten restringir o realizar un seguimiento del espacio en disco y del número de archivos que usan un usuario, un grupo o un qtree.



== Creación de volúmenes de FlexVol en el segundo nodo de una alta disponibilidad configuración

De forma predeterminada, Cloud Manager crea volúmenes en el primer nodo de una configuración de alta disponibilidad. Si necesita una configuración activo-activo, en la que ambos nodos sirven datos a los clientes, debe crear agregados y volúmenes en el segundo nodo.

.Pasos
. En la página entornos de trabajo, haga doble clic en el nombre del entorno de trabajo de Cloud Volumes ONTAP en el que desea gestionar agregados.
. Haga clic en el icono de menú y, a continuación, haga clic en *Avanzado > asignación avanzada*.
. Haga clic en *Agregar agregado* y, a continuación, cree el agregado.
. Para Home Node, elija el segundo nodo del par de alta disponibilidad.
. Después de que Cloud Manager cree el agregado, selecciónelo y, a continuación, haga clic en *Crear volumen*.
. Introduzca los detalles del nuevo volumen y, a continuación, haga clic en *Crear*.


.Después de terminar
Puede crear volúmenes adicionales en este agregado si es necesario.


IMPORTANT: En el caso de parejas de alta disponibilidad implementadas en varias zonas de disponibilidad de AWS, debe montar el volumen en clientes mediante la dirección IP flotante del nodo en el que reside el volumen.



== Creación de agregados

Puede crear agregados usted mismo o dejar que Cloud Manager lo haga por usted cuando cree volúmenes. La ventaja de crear los agregados usted mismo es que puede elegir el tamaño de disco subyacente, lo que le permite configurar el agregado para la capacidad o el rendimiento que necesita.

.Pasos
. En la página entornos de trabajo, haga doble clic en el nombre de la instancia de Cloud Volumes ONTAP en la que desea gestionar agregados.
. Haga clic en el icono de menú y, a continuación, haga clic en *Avanzado > asignación avanzada*.
. Haga clic en *Agregar agregado* y, a continuación, especifique los detalles para el agregado.
+
Para obtener ayuda con el tipo de disco y el tamaño de disco, consulte link:task_planning_your_config.html["Planificación de la configuración"].

. Haga clic en *Ir* y, a continuación, haga clic en *aprobar y adquirir*.




== Conectar una LUN a un host

Cuando se crea un volumen iSCSI, Cloud Manager crea automáticamente un LUN. Lo hemos hecho sencillo creando sólo una LUN por volumen, por lo que no hay que realizar ninguna gestión. Después de crear el volumen, utilice el IQN para conectarse con el LUN desde los hosts.

Tenga en cuenta lo siguiente:

. La gestión automática de la capacidad de Cloud Manager no se aplica a las LUN. Cuando Cloud Manager crea un LUN, deshabilita la función de crecimiento automático.
. Puede crear LUN adicionales desde System Manager o desde la CLI.


.Pasos
. En la página Working Environments, haga doble clic en el entorno de trabajo de Cloud Volumes ONTAP en el que desea gestionar los volúmenes.
. Seleccione un volumen y, a continuación, haga clic en *IQN objetivo*.
. Haga clic en *Copiar* para copiar el nombre del IQN.
. Configurar una conexión iSCSI desde el host al LUN.
+
** http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-rhel-cg/GUID-15E8C226-BED5-46D0-BAED-379EA4311340.html["Configuración exprés de iSCSI de ONTAP 9 para Red Hat Enterprise Linux: Iniciar las sesiones iSCSI con el destino"^]
** http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-cpg/GUID-857453EC-90E9-4AB6-B543-83827CF374BF.html["Configuración exprés de iSCSI para Windows de ONTAP 9: Iniciar sesiones iSCSI con el destino"^]






== Uso de volúmenes de FlexCache para acelerar el acceso a los datos

Un volumen FlexCache es un volumen de almacenamiento que almacena en caché datos de lectura NFS de un volumen de origen (o origen). Las lecturas posteriores a los datos almacenados en caché hacen que el acceso a los datos sea más rápido.

Puede usar volúmenes de FlexCache para acelerar el acceso a los datos o para descargar el tráfico de volúmenes con un acceso frecuente. Los volúmenes FlexCache ayudan a mejorar el rendimiento, en especial cuando los clientes necesitan acceder a los mismos datos en repetidas ocasiones, ya que los datos pueden ofrecerse directamente sin tener que acceder al volumen de origen. Los volúmenes FlexCache funcionan bien con cargas de trabajo del sistema que requieren una gran cantidad de lecturas.

Cloud Manager no proporciona gestión de volúmenes de FlexCache en este momento, pero se puede usar la interfaz de línea de comandos de ONTAP o ONTAP System Manager para crear y gestionar volúmenes de FlexCache:

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-fc-mgmt/home.html["Guía completa de volúmenes de FlexCache para un acceso más rápido a los datos"^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-07F4C213-076D-4FE8-A8E3-410F49498D49.html["Creación de volúmenes de FlexCache en System Manager"^]


A partir del lanzamiento de la versión 3.7.2, Cloud Manager genera una licencia de FlexCache para todos los nuevos sistemas de Cloud Volumes ONTAP. La licencia incluye un límite de uso de 500 GB.


NOTE: Para generar la licencia, Cloud Manager necesita acceder a \https://ipa-signer.cloudmanager.netapp.com. Asegúrese de que se puede acceder a esta URL desde el firewall.

video::PBNPVRUeT1o[youtube,width=848,height=480]